# Generated by Django 4.1.2 on 2022-10-13 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=35, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(default="images/007.jpg", upload_to="images"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=20, unique=True)),
                (
                    "image",
                    models.ImageField(
                        default="images/ing_def.webp", upload_to="images"
                    ),
                ),
                (
                    "ing_recipe",
                    models.ManyToManyField(
                        related_name="ingredient", to="polls.recipe"
                    ),
                ),
            ],
        ),
    ]
